version: "3.3"
services:

  backend:
    ports:
      - "8000:80"
    command: /start-reload.sh
    volumes:
      - ./backend:/app
      - ../nanopub:/opt/nanopub
      # - ../ontogpt:/opt/ontogpt
    environment:
      - FRONTEND_URL=http://localhost:19006
      - INSTALL_DEV=true
      - DEV_MODE=true
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
        DEV_MODE: "true"



  # frontend:
  #   build:
  #     context: ./frontend
  #     args:
  #       FRONTEND_URL: ${FRONTEND_URL:-https://collaboratory.semanticscience.org}
  #       API_URL: ${API_URL:-https://api.collaboratory.semanticscience.org}
  #       ORCID_CLIENT_ID: ${ORCID_CLIENT_ID}
  #   ports:
  #   - 4000:4000
  #   command: "yarn dev"
  #   environment:
  #     NEXT_PUBLIC_API_URL: https://api.collaboratory.semanticscience.org
  #   volumes:
  #   - ./frontend:/webapp
