version: "3.3"
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    env_file:
      - .env
    volumes:
      - /data/knowledge-collaboratory/ner-models:/data/ner-models
      - /data/knowledge-collaboratory/nanopub-keystore:/data/nanopub-keystore
