version: "3.3"
services:

  backend:
    ports:
      - "80:80"
    command: /start-reload.sh
    volumes:
      - ./backend:/app
    environment:
      - FRONTEND_URL=http://localhost:19006
      - INSTALL_DEV=true
      - DEV_MODE=true
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
        DEV_MODE: true


  ## We recommend to use `yarn dev` locally to start it (easier than in docker for dev)
  # frontend:
  #   build:
  #     context: ./frontend
  #     args:
  #       FRONTEND_ENV: dev
  #       API_URL: http://localhost
  #   ports:
  #     - 19006:19006
  #     - 4000:4000
  #   command: "yarn dev"
  #   environment:
  #     - API_URL=http://localhost
  #   # volumes:
  #   #   - ./frontend:/webapp

