version: "3.3"
services:

  backend:
    # image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    env_file:
      - .env
    volumes:
      - /data/knowledge-collaboratory/ner-models:/data/ner-models
      - /data/knowledge-collaboratory/nanopub-keystore:/data/nanopub-keystore


  # frontend:
  #   build:
  #     # context: ./frontend
  #     context: ./nextjs-frontend
  #     args:
  #       FRONTEND_URL: ${FRONTEND_URL:-https://collaboratory.semanticscience.org}
  #       API_URL: ${API_URL:-https://api.collaboratory.semanticscience.org}
  #       ORCID_CLIENT_ID: ${ORCID_CLIENT_ID}
  #   ports:
  #   - 3000:3000
  #   environment:
  #     API_URL: https://api.collaboratory.semanticscience.org
  #     VIRTUAL_HOST: collaboratory.semanticscience.org
  #     LETSENCRYPT_HOST: collaboratory.semanticscience.org
  #     VIRTUAL_PORT: 3000