version: "3.3"
services:

  backend:
    restart: unless-stopped
    environment:
      FRONTEND_URL: ${FRONTEND_URL:-https://collaboratory.semanticscience.org}
      API_URL: ${API_URL:-https://api.collaboratory.semanticscience.org}
      ORCID_CLIENT_ID: ${ORCID_CLIENT_ID}
      ORCID_CLIENT_SECRET: ${ORCID_CLIENT_SECRET}
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: api.collaboratory.semanticscience.org
      LETSENCRYPT_HOST: api.collaboratory.semanticscience.org
    volumes:
      - /data/knowledge-collaboratory/ner-models:/data/ner-models
      - /data/knowledge-collaboratory/nanopub-keystore:/data/nanopub-keystore

  frontend:
    build:
      context: ./frontend
      args:
        API_URL: ${API_URL:-https://api.collaboratory.semanticscience.org}
        FRONTEND_URL: ${FRONTEND_URL:-https://collaboratory.semanticscience.org}
        ORCID_CLIENT_ID: ${ORCID_CLIENT_ID}
    restart: unless-stopped
    environment:
      # NEXT_PUBLIC_API_URL: ${API_URL:-https://api.collaboratory.semanticscience.org}
      # NEXT_PUBLIC_FRONTEND_URL: ${FRONTEND_URL:-https://collaboratory.semanticscience.org}
      # ORCID_CLIENT_ID: ${ORCID_CLIENT_ID}
      VIRTUAL_HOST: collaboratory.semanticscience.org
      LETSENCRYPT_HOST: collaboratory.semanticscience.org
      VIRTUAL_PORT: 4000
