import React from "react";
import { useTheme } from '@mui/material/styles';

const settings = {
  apiUrl: process.env.API_URL || 'http://localhost',
  restUrl: ((process.env.API_URL) ? process.env.API_URL + '' : null) || 'http://localhost',
  docsUrl: ((process.env.API_URL) ? process.env.API_URL + '/docs' : null) || 'http://localhost/docs',
  graphqlUrl: ((process.env.API_URL) ? process.env.API_URL + '/graphql' : null) || 'http://localhost/graphql',
  OauthRedirectUri: process.env.OAUTH_REDIRECT_FRONTEND || "http://localhost:19006",
  nanopubGrlcUrl: process.env.GRLC_URL || "https://grlc.np.dumontierlab.com/api/local/local",
  // http://grlc.nanopubs.lod.labs.vu.nl/api/local/local
}

const getUrlHtml = (urlString: string) => {
  const theme = useTheme();
  if(/^(?:node[0-9]+)|((https?|ftp):.*)$/.test(urlString)) {
    // Process URIs
    return <a href={urlString}  target="_blank" rel="noopener noreferrer"
        style={{color: theme.palette.primary.main,
          textDecoration: 'none',
          // '&:hover': {
          //   color: theme.palette.primary.light,
          //   textDecoration: 'none',}
          }}>{urlString}</a>
  } else {
    return urlString
  }
}

// https://biolink.github.io/biolink-model/docs/predicates.html
const predicatesList = [
  {id: 'https://w3id.org/biolink/vocab/treats', curie: 'biolink:treats', label: 'Treats', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/treated_by', curie: 'biolink:treated_by', label: 'Treated by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/interacts_with', curie: 'biolink:interacts_with', label: 'Interacts with', type: 'BioLink'},

  {id: 'https://w3id.org/biolink/vocab/abundance_affected_by', curie: 'biolink:abundance_affected_by', label: 'abundance affected by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/abundance_decreased_by', curie: 'biolink:abundance_decreased_by', label: 'abundance decreased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/abundance_increased_by', curie: 'biolink:abundance_increased_by', label: 'abundance increased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/active_in', curie: 'biolink:active_in', label: 'active in', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/actively_involved_in', curie: 'biolink:actively_involved_in', label: 'actively involved in', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/actively_involves', curie: 'biolink:actively_involves', label: 'actively involves', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/activity_affected_by', curie: 'biolink:activity_affected_by', label: 'activity affected by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/activity_decreased_by', curie: 'biolink:activity_decreased_by', label: 'activity decreased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/activity_increased_by', curie: 'biolink:activity_increased_by', label: 'activity increased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/acts_upstream_of', curie: 'biolink:acts_upstream_of', label: 'acts upstream of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/acts_upstream_of_negative_effect', curie: 'biolink:acts_upstream_of_negative_effect', label: 'acts upstream of negative effect', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/acts_upstream_of_or_within', curie: 'biolink:acts_upstream_of_or_within', label: 'acts upstream of or within', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/acts_upstream_of_or_within_negative_effect', curie: 'biolink:acts_upstream_of_or_within_negative_effect', label: 'acts upstream of or within negative effect', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/acts_upstream_of_or_within_positive_effect', curie: 'biolink:acts_upstream_of_or_within_positive_effect', label: 'acts upstream of or within positive effect', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/acts_upstream_of_positive_effect', curie: 'biolink:acts_upstream_of_positive_effect', label: 'acts upstream of positive effect', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/adverse_event_caused_by', curie: 'biolink:adverse_event_caused_by', label: 'adverse event caused by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affected_by', curie: 'biolink:affected_by', label: 'affected by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects', curie: 'biolink:affects', label: 'affects', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects_abundance_of', curie: 'biolink:affects_abundance_of', label: 'affects abundance of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects_activity_of', curie: 'biolink:affects_activity_of', label: 'affects activity of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects_degradation_of', curie: 'biolink:affects_degradation_of', label: 'affects degradation of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects_expression_in', curie: 'biolink:affects_expression_in', label: 'affects expression in', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects_expression_of', curie: 'biolink:affects_expression_of', label: 'affects expression of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects_folding_of', curie: 'biolink:affects_folding_of', label: 'affects folding of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects_localization_of', curie: 'biolink:affects_localization_of', label: 'affects localization of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects_metabolic_processing_of', curie: 'biolink:affects_metabolic_processing_of', label: 'affects metabolic processing of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects_molecular_modification_of', curie: 'biolink:affects_molecular_modification_of', label: 'affects molecular modification of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects_mutation_rate_of', curie: 'biolink:affects_mutation_rate_of', label: 'affects mutation rate of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects_response_to', curie: 'biolink:affects_response_to', label: 'affects response to', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects_risk_for', curie: 'biolink:affects_risk_for', label: 'affects risk for', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects_secretion_of', curie: 'biolink:affects_secretion_of', label: 'affects secretion of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects_splicing_of', curie: 'biolink:affects_splicing_of', label: 'affects splicing of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects_stability_of', curie: 'biolink:affects_stability_of', label: 'affects stability of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects_synthesis_of', curie: 'biolink:affects_synthesis_of', label: 'affects synthesis of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects_transport_of', curie: 'biolink:affects_transport_of', label: 'affects transport of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/affects_uptake_of', curie: 'biolink:affects_uptake_of', label: 'affects uptake of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/ameliorates', curie: 'biolink:ameliorates', label: 'ameliorates', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/approved_for_treatment_by', curie: 'biolink:approved_for_treatment_by', label: 'approved for treatment by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/approved_to_treat', curie: 'biolink:approved_to_treat', label: 'approved to treat', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/associated_with', curie: 'biolink:associated_with', label: 'associated with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/associated_with_resistance_to', curie: 'biolink:associated_with_resistance_to', label: 'associated with resistance to', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/associated_with_sensitivity_to', curie: 'biolink:associated_with_sensitivity_to', label: 'associated with sensitivity to', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/author', curie: 'biolink:author', label: 'author', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/biomarker_for', curie: 'biolink:biomarker_for', label: 'biomarker for', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/broad_match', curie: 'biolink:broad_match', label: 'broad match', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/capability_of', curie: 'biolink:capability_of', label: 'capability of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/capable_of', curie: 'biolink:capable_of', label: 'capable of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/catalyzes', curie: 'biolink:catalyzes', label: 'catalyzes', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/caused_by', curie: 'biolink:caused_by', label: 'caused by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/causes', curie: 'biolink:causes', label: 'causes', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/causes_adverse_event', curie: 'biolink:causes_adverse_event', label: 'causes adverse event', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/chemically_interacts_with', curie: 'biolink:chemically_interacts_with', label: 'chemically interacts with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/chemically_similar_to', curie: 'biolink:chemically_similar_to', label: 'chemically similar to', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/close_match', curie: 'biolink:close_match', label: 'close match', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/coexists_with', curie: 'biolink:coexists_with', label: 'coexists with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/coexpressed_with', curie: 'biolink:coexpressed_with', label: 'coexpressed with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/colocalizes_with', curie: 'biolink:colocalizes_with', label: 'colocalizes with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/completed_by', curie: 'biolink:completed_by', label: 'completed by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/composed_primarily_of', curie: 'biolink:composed_primarily_of', label: 'composed primarily of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/condition_associated_with_gene', curie: 'biolink:condition_associated_with_gene', label: 'condition associated with gene', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/consumed_by', curie: 'biolink:consumed_by', label: 'consumed by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/consumes', curie: 'biolink:consumes', label: 'consumes', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/contains_process', curie: 'biolink:contains_process', label: 'contains process', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/contraindicated_for', curie: 'biolink:contraindicated_for', label: 'contraindicated for', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/contributes_to', curie: 'biolink:contributes_to', label: 'contributes to', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/contribution_from', curie: 'biolink:contribution_from', label: 'contribution from', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/contributor', curie: 'biolink:contributor', label: 'contributor', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/correlated_with', curie: 'biolink:correlated_with', label: 'correlated with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/decreased_amount_in', curie: 'biolink:decreased_amount_in', label: 'decreased amount in', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/decreases_abundance_of', curie: 'biolink:decreases_abundance_of', label: 'decreases abundance of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/decreases_activity_of', curie: 'biolink:decreases_activity_of', label: 'decreases activity of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/decreases_degradation_of', curie: 'biolink:decreases_degradation_of', label: 'decreases degradation of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/decreases_expression_of', curie: 'biolink:decreases_expression_of', label: 'decreases expression of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/decreases_folding_of', curie: 'biolink:decreases_folding_of', label: 'decreases folding of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/decreases_localization_of', curie: 'biolink:decreases_localization_of', label: 'decreases localization of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/decreases_metabolic_processing_of', curie: 'biolink:decreases_metabolic_processing_of', label: 'decreases metabolic processing of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/decreases_molecular_interaction', curie: 'biolink:decreases_molecular_interaction', label: 'decreases molecular interaction', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/decreases_molecular_modification_of', curie: 'biolink:decreases_molecular_modification_of', label: 'decreases molecular modification of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/decreases_mutation_rate_of', curie: 'biolink:decreases_mutation_rate_of', label: 'decreases mutation rate of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/decreases_response_to', curie: 'biolink:decreases_response_to', label: 'decreases response to', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/decreases_secretion_of', curie: 'biolink:decreases_secretion_of', label: 'decreases secretion of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/decreases_splicing_of', curie: 'biolink:decreases_splicing_of', label: 'decreases splicing of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/decreases_stability_of', curie: 'biolink:decreases_stability_of', label: 'decreases stability of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/decreases_synthesis_of', curie: 'biolink:decreases_synthesis_of', label: 'decreases synthesis of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/decreases_transport_of', curie: 'biolink:decreases_transport_of', label: 'decreases transport of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/decreases_uptake_of', curie: 'biolink:decreases_uptake_of', label: 'decreases uptake of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/degradation_affected_by', curie: 'biolink:degradation_affected_by', label: 'degradation affected by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/degradation_decreased_by', curie: 'biolink:degradation_decreased_by', label: 'degradation decreased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/degradation_increased_by', curie: 'biolink:degradation_increased_by', label: 'degradation increased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/derives_from', curie: 'biolink:derives_from', label: 'derives from', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/derives_into', curie: 'biolink:derives_into', label: 'derives into', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/develops_from', curie: 'biolink:develops_from', label: 'develops from', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/develops_into', curie: 'biolink:develops_into', label: 'develops into', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/diagnoses', curie: 'biolink:diagnoses', label: 'diagnoses', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/directly_interacts_with', curie: 'biolink:directly_interacts_with', label: 'directly interacts with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/disease_has_basis_in', curie: 'biolink:disease_has_basis_in', label: 'disease has basis in', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/disease_has_location', curie: 'biolink:disease_has_location', label: 'disease has location', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/disrupted_by', curie: 'biolink:disrupted_by', label: 'disrupted by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/disrupts', curie: 'biolink:disrupts', label: 'disrupts', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/editor', curie: 'biolink:editor', label: 'editor', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/enabled_by', curie: 'biolink:enabled_by', label: 'enabled by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/enables', curie: 'biolink:enables', label: 'enables', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/entity_negatively_regulated_by_entity', curie: 'biolink:entity_negatively_regulated_by_entity', label: 'entity negatively regulated by entity', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/entity_negatively_regulates_entity', curie: 'biolink:entity_negatively_regulates_entity', label: 'entity negatively regulates entity', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/entity_positively_regulated_by_entity', curie: 'biolink:entity_positively_regulated_by_entity', label: 'entity positively regulated by entity', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/entity_positively_regulates_entity', curie: 'biolink:entity_positively_regulates_entity', label: 'entity positively regulates entity', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/entity_regulated_by_entity', curie: 'biolink:entity_regulated_by_entity', label: 'entity regulated by entity', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/entity_regulates_entity', curie: 'biolink:entity_regulates_entity', label: 'entity regulates entity', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/exacerbates', curie: 'biolink:exacerbates', label: 'exacerbates', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/exact_match', curie: 'biolink:exact_match', label: 'exact match', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/expressed_in', curie: 'biolink:expressed_in', label: 'expressed in', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/expresses', curie: 'biolink:expresses', label: 'expresses', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/expression_affected_by', curie: 'biolink:expression_affected_by', label: 'expression affected by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/expression_decreased_by', curie: 'biolink:expression_decreased_by', label: 'expression decreased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/expression_increased_by', curie: 'biolink:expression_increased_by', label: 'expression increased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/folding_affected_by', curie: 'biolink:folding_affected_by', label: 'folding affected by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/folding_decreased_by', curie: 'biolink:folding_decreased_by', label: 'folding decreased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/folding_increased_by', curie: 'biolink:folding_increased_by', label: 'folding increased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/food_component_of', curie: 'biolink:food_component_of', label: 'food component of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/gene_associated_with_condition', curie: 'biolink:gene_associated_with_condition', label: 'gene associated with condition', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/gene_product_of', curie: 'biolink:gene_product_of', label: 'gene product of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/genetic_association', curie: 'biolink:genetic_association', label: 'genetic association', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/genetically_interacts_with', curie: 'biolink:genetically_interacts_with', label: 'genetically interacts with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_active_ingredient', curie: 'biolink:has_active_ingredient', label: 'has active ingredient', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_biomarker', curie: 'biolink:has_biomarker', label: 'has biomarker', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_catalyst', curie: 'biolink:has_catalyst', label: 'has catalyst', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_completed', curie: 'biolink:has_completed', label: 'has completed', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_contraindication', curie: 'biolink:has_contraindication', label: 'has contraindication', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_decreased_amount', curie: 'biolink:has_decreased_amount', label: 'has decreased amount', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_excipient', curie: 'biolink:has_excipient', label: 'has excipient', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_food_component', curie: 'biolink:has_food_component', label: 'has food component', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_frameshift_variant', curie: 'biolink:has_frameshift_variant', label: 'has frameshift variant', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_gene_product', curie: 'biolink:has_gene_product', label: 'has gene product', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_increased_amount', curie: 'biolink:has_increased_amount', label: 'has increased amount', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_input', curie: 'biolink:has_input', label: 'has input', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_manifestation', curie: 'biolink:has_manifestation', label: 'has manifestation', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_metabolite', curie: 'biolink:has_metabolite', label: 'has metabolite', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_missense_variant', curie: 'biolink:has_missense_variant', label: 'has missense variant', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_molecular_consequence', curie: 'biolink:has_molecular_consequence', label: 'has molecular consequence', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_nearby_variant', curie: 'biolink:has_nearby_variant', label: 'has nearby variant', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_negative_upstream_actor', curie: 'biolink:has_negative_upstream_actor', label: 'has negative upstream actor', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_negative_upstream_or_within_actor', curie: 'biolink:has_negative_upstream_or_within_actor', label: 'has negative upstream or within actor', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_non_coding_variant', curie: 'biolink:has_non_coding_variant', label: 'has non coding variant', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_nonsense_variant', curie: 'biolink:has_nonsense_variant', label: 'has nonsense variant', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_not_completed', curie: 'biolink:has_not_completed', label: 'has not completed', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_nutrient', curie: 'biolink:has_nutrient', label: 'has nutrient', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_output', curie: 'biolink:has_output', label: 'has output', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_part', curie: 'biolink:has_part', label: 'has part', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_participant', curie: 'biolink:has_participant', label: 'has participant', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_phenotype', curie: 'biolink:has_phenotype', label: 'has phenotype', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_plasma_membrane_part', curie: 'biolink:has_plasma_membrane_part', label: 'has plasma membrane part', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_positive_upstream_actor', curie: 'biolink:has_positive_upstream_actor', label: 'has positive upstream actor', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_positive_upstream_or_within_actor', curie: 'biolink:has_positive_upstream_or_within_actor', label: 'has positive upstream or within actor', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_real_world_evidence_of_association_with', curie: 'biolink:has_real_world_evidence_of_association_with', label: 'has real world evidence of association with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_sequence_location', curie: 'biolink:has_sequence_location', label: 'has sequence location', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_sequence_variant', curie: 'biolink:has_sequence_variant', label: 'has sequence variant', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_splice_site_variant', curie: 'biolink:has_splice_site_variant', label: 'has splice site variant', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_substrate', curie: 'biolink:has_substrate', label: 'has substrate', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_synonymous_variant', curie: 'biolink:has_synonymous_variant', label: 'has synonymous variant', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_upstream_actor', curie: 'biolink:has_upstream_actor', label: 'has upstream actor', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_upstream_or_within_actor', curie: 'biolink:has_upstream_or_within_actor', label: 'has upstream or within actor', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_variant_part', curie: 'biolink:has_variant_part', label: 'has variant part', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/homologous_to', curie: 'biolink:homologous_to', label: 'homologous to', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/in_cell_population_with', curie: 'biolink:in_cell_population_with', label: 'in cell population with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/in_complex_with', curie: 'biolink:in_complex_with', label: 'in complex with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/in_linkage_disequilibrium_with', curie: 'biolink:in_linkage_disequilibrium_with', label: 'in linkage disequilibrium with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/in_pathway_with', curie: 'biolink:in_pathway_with', label: 'in pathway with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/in_taxon', curie: 'biolink:in_taxon', label: 'in taxon', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/increased_amount_of', curie: 'biolink:increased_amount_of', label: 'increased amount of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/increases_abundance_of', curie: 'biolink:increases_abundance_of', label: 'increases abundance of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/increases_activity_of', curie: 'biolink:increases_activity_of', label: 'increases activity of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/increases_degradation_of', curie: 'biolink:increases_degradation_of', label: 'increases degradation of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/increases_expression_of', curie: 'biolink:increases_expression_of', label: 'increases expression of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/increases_folding_of', curie: 'biolink:increases_folding_of', label: 'increases folding of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/increases_localization_of', curie: 'biolink:increases_localization_of', label: 'increases localization of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/increases_metabolic_processing_of', curie: 'biolink:increases_metabolic_processing_of', label: 'increases metabolic processing of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/increases_molecular_interaction', curie: 'biolink:increases_molecular_interaction', label: 'increases molecular interaction', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/increases_molecular_modification_of', curie: 'biolink:increases_molecular_modification_of', label: 'increases molecular modification of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/increases_mutation_rate_of', curie: 'biolink:increases_mutation_rate_of', label: 'increases mutation rate of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/increases_response_to', curie: 'biolink:increases_response_to', label: 'increases response to', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/increases_secretion_of', curie: 'biolink:increases_secretion_of', label: 'increases secretion of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/increases_splicing_of', curie: 'biolink:increases_splicing_of', label: 'increases splicing of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/increases_stability_of', curie: 'biolink:increases_stability_of', label: 'increases stability of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/increases_synthesis_of', curie: 'biolink:increases_synthesis_of', label: 'increases synthesis of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/increases_transport_of', curie: 'biolink:increases_transport_of', label: 'increases transport of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/increases_uptake_of', curie: 'biolink:increases_uptake_of', label: 'increases uptake of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/is_active_ingredient_of', curie: 'biolink:is_active_ingredient_of', label: 'is active ingredient of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/is_diagnosed_by', curie: 'biolink:is_diagnosed_by', label: 'is diagnosed by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/is_excipient_of', curie: 'biolink:is_excipient_of', label: 'is excipient of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/is_frameshift_variant_of', curie: 'biolink:is_frameshift_variant_of', label: 'is frameshift variant of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/is_input_of', curie: 'biolink:is_input_of', label: 'is input of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/is_metabolite_of', curie: 'biolink:is_metabolite_of', label: 'is metabolite of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/is_missense_variant_of', curie: 'biolink:is_missense_variant_of', label: 'is missense variant of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/is_molecular_consequence_of', curie: 'biolink:is_molecular_consequence_of', label: 'is molecular consequence of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/is_nearby_variant_of', curie: 'biolink:is_nearby_variant_of', label: 'is nearby variant of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/is_non_coding_variant_of', curie: 'biolink:is_non_coding_variant_of', label: 'is non coding variant of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/is_nonsense_variant_of', curie: 'biolink:is_nonsense_variant_of', label: 'is nonsense variant of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/is_output_of', curie: 'biolink:is_output_of', label: 'is output of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/is_sequence_variant_of', curie: 'biolink:is_sequence_variant_of', label: 'is sequence variant of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/is_splice_site_variant_of', curie: 'biolink:is_splice_site_variant_of', label: 'is splice site variant of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/is_substrate_of', curie: 'biolink:is_substrate_of', label: 'is substrate of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/is_synonymous_variant_of', curie: 'biolink:is_synonymous_variant_of', label: 'is synonymous variant of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/lacks_part', curie: 'biolink:lacks_part', label: 'lacks part', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/localization_affected_by', curie: 'biolink:localization_affected_by', label: 'localization affected by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/localization_decreased_by', curie: 'biolink:localization_decreased_by', label: 'localization decreased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/localization_increased_by', curie: 'biolink:localization_increased_by', label: 'localization increased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/located_in', curie: 'biolink:located_in', label: 'located in', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/location_of', curie: 'biolink:location_of', label: 'location of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/manifestation_of', curie: 'biolink:manifestation_of', label: 'manifestation of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/mentioned_by', curie: 'biolink:mentioned_by', label: 'mentioned by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/mentions', curie: 'biolink:mentions', label: 'mentions', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/metabolic_processing_affected_by', curie: 'biolink:metabolic_processing_affected_by', label: 'metabolic processing affected by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/metabolic_processing_decreased_by', curie: 'biolink:metabolic_processing_decreased_by', label: 'metabolic processing decreased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/metabolic_processing_increased_by', curie: 'biolink:metabolic_processing_increased_by', label: 'metabolic processing increased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/missing_from', curie: 'biolink:missing_from', label: 'missing from', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/model_of', curie: 'biolink:model_of', label: 'model of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/models', curie: 'biolink:models', label: 'models', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/molecular_interaction_decreased_by', curie: 'biolink:molecular_interaction_decreased_by', label: 'molecular interaction decreased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/molecular_interaction_increased_by', curie: 'biolink:molecular_interaction_increased_by', label: 'molecular interaction increased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/molecular_modification_affected_by', curie: 'biolink:molecular_modification_affected_by', label: 'molecular modification affected by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/molecular_modification_decreased_by', curie: 'biolink:molecular_modification_decreased_by', label: 'molecular modification decreased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/molecular_modification_increased_by', curie: 'biolink:molecular_modification_increased_by', label: 'molecular modification increased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/molecularly_interacts_with', curie: 'biolink:molecularly_interacts_with', label: 'molecularly interacts with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/mutation_rate_affected_by', curie: 'biolink:mutation_rate_affected_by', label: 'mutation rate affected by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/mutation_rate_decreased_by', curie: 'biolink:mutation_rate_decreased_by', label: 'mutation rate decreased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/mutation_rate_increased_by', curie: 'biolink:mutation_rate_increased_by', label: 'mutation rate increased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/narrow_match', curie: 'biolink:narrow_match', label: 'narrow match', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/negatively_correlated_with', curie: 'biolink:negatively_correlated_with', label: 'negatively correlated with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/not_completed_by', curie: 'biolink:not_completed_by', label: 'not completed by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/nutrient_of', curie: 'biolink:nutrient_of', label: 'nutrient of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/occurs_in', curie: 'biolink:occurs_in', label: 'occurs in', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/occurs_together_in_literature_with', curie: 'biolink:occurs_together_in_literature_with', label: 'occurs together in literature with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/opposite_of', curie: 'biolink:opposite_of', label: 'opposite of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/orthologous_to', curie: 'biolink:orthologous_to', label: 'orthologous to', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/overlaps', curie: 'biolink:overlaps', label: 'overlaps', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/paralogous_to', curie: 'biolink:paralogous_to', label: 'paralogous to', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/part_of', curie: 'biolink:part_of', label: 'part of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/participates_in', curie: 'biolink:participates_in', label: 'participates in', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/phenotype_of', curie: 'biolink:phenotype_of', label: 'phenotype of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/physically_interacts_with', curie: 'biolink:physically_interacts_with', label: 'physically interacts with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/plasma_membrane_part_of', curie: 'biolink:plasma_membrane_part_of', label: 'plasma membrane part of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/positively_correlated_with', curie: 'biolink:positively_correlated_with', label: 'positively correlated with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/preceded_by', curie: 'biolink:preceded_by', label: 'preceded by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/precedes', curie: 'biolink:precedes', label: 'precedes', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/predisposes', curie: 'biolink:predisposes', label: 'predisposes', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/prevented_by', curie: 'biolink:prevented_by', label: 'prevented by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/prevents', curie: 'biolink:prevents', label: 'prevents', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/process_negatively_regulated_by_process', curie: 'biolink:process_negatively_regulated_by_process', label: 'process negatively regulated by process', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/process_negatively_regulates_process', curie: 'biolink:process_negatively_regulates_process', label: 'process negatively regulates process', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/process_positively_regulated_by_process', curie: 'biolink:process_positively_regulated_by_process', label: 'process positively regulated by process', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/process_positively_regulates_process', curie: 'biolink:process_positively_regulates_process', label: 'process positively regulates process', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/process_regulated_by_process', curie: 'biolink:process_regulated_by_process', label: 'process regulated by process', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/process_regulates_process', curie: 'biolink:process_regulates_process', label: 'process regulates process', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/produced_by', curie: 'biolink:produced_by', label: 'produced by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/produces', curie: 'biolink:produces', label: 'produces', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/provider', curie: 'biolink:provider', label: 'provider', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/publisher', curie: 'biolink:publisher', label: 'publisher', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/related_condition', curie: 'biolink:related_condition', label: 'related condition', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/related_to', curie: 'biolink:related_to', label: 'related to', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/related_to_at_concept_level', curie: 'biolink:related_to_at_concept_level', label: 'related to at concept level', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/related_to_at_instance_level', curie: 'biolink:related_to_at_instance_level', label: 'related to at instance level', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/resistance_associated_with', curie: 'biolink:resistance_associated_with', label: 'resistance associated with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/response_affected_by', curie: 'biolink:response_affected_by', label: 'response affected by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/response_decreased_by', curie: 'biolink:response_decreased_by', label: 'response decreased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/response_increased_by', curie: 'biolink:response_increased_by', label: 'response increased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/risk_affected_by', curie: 'biolink:risk_affected_by', label: 'risk affected by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/same_as', curie: 'biolink:same_as', label: 'same as', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/secretion_affected_by', curie: 'biolink:secretion_affected_by', label: 'secretion affected by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/secretion_decreased_by', curie: 'biolink:secretion_decreased_by', label: 'secretion decreased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/secretion_increased_by', curie: 'biolink:secretion_increased_by', label: 'secretion increased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/sensitivity_associated_with', curie: 'biolink:sensitivity_associated_with', label: 'sensitivity associated with', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/sequence_location_of', curie: 'biolink:sequence_location_of', label: 'sequence location of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/similar_to', curie: 'biolink:similar_to', label: 'similar to', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/splicing_affected_by', curie: 'biolink:splicing_affected_by', label: 'splicing affected by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/splicing_decreased_by', curie: 'biolink:splicing_decreased_by', label: 'splicing decreased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/splicing_increased_by', curie: 'biolink:splicing_increased_by', label: 'splicing increased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/stability_affected_by', curie: 'biolink:stability_affected_by', label: 'stability affected by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/stability_decreased_by', curie: 'biolink:stability_decreased_by', label: 'stability decreased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/stability_increased_by', curie: 'biolink:stability_increased_by', label: 'stability increased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/subclass_of', curie: 'biolink:subclass_of', label: 'subclass of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/superclass_of', curie: 'biolink:superclass_of', label: 'superclass of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/synthesis_affected_by', curie: 'biolink:synthesis_affected_by', label: 'synthesis affected by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/synthesis_decreased_by', curie: 'biolink:synthesis_decreased_by', label: 'synthesis decreased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/synthesis_increased_by', curie: 'biolink:synthesis_increased_by', label: 'synthesis increased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/taxon_of', curie: 'biolink:taxon_of', label: 'taxon of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/temporally_related_to', curie: 'biolink:temporally_related_to', label: 'temporally related to', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/transcribed_from', curie: 'biolink:transcribed_from', label: 'transcribed from', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/transcribed_to', curie: 'biolink:transcribed_to', label: 'transcribed to', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/translates_to', curie: 'biolink:translates_to', label: 'translates to', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/translation_of', curie: 'biolink:translation_of', label: 'translation of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/transport_affected_by', curie: 'biolink:transport_affected_by', label: 'transport affected by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/transport_decreased_by', curie: 'biolink:transport_decreased_by', label: 'transport decreased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/transport_increased_by', curie: 'biolink:transport_increased_by', label: 'transport increased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/uptake_affected_by', curie: 'biolink:uptake_affected_by', label: 'uptake affected by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/uptake_decreased_by', curie: 'biolink:uptake_decreased_by', label: 'uptake decreased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/uptake_increased_by', curie: 'biolink:uptake_increased_by', label: 'uptake increased by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/variant_part_of', curie: 'biolink:variant_part_of', label: 'variant part of', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/xenologous_to', curie: 'biolink:xenologous_to', label: 'xenologous to', type: 'BioLink'},
]

// https://biolink.github.io/biolink-model/docs/edge_properties.html
const propertiesList = [
  {id: 'https://w3id.org/biolink/vocab/has_population_context', curie: 'biolink:has_population_context', label: 'has population context', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_temporal_context', curie: 'biolink:has_temporal_context', label: 'has temporal context', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/publications', curie: 'biolink:publications', label: 'publications', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_confidence_level', curie: 'biolink:has_confidence_level', label: 'has confidence level', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/has_evidence', curie: 'biolink:has_evidence', label: 'has evidence', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/supporting_data_source', curie: 'biolink:supporting_data_source', label: 'supporting data source', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/stoichiometry', curie: 'biolink:stoichiometry', label: 'stoichiometry', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/FDA_approval_status', curie: 'biolink:FDA_approval_status', label: 'FDA approval status', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/aggregator_knowledge_source', curie: 'biolink:aggregator_knowledge_source', label: 'aggregator knowledge source', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/associated_environmental_context', curie: 'biolink:associated_environmental_context', label: 'associated environmental context', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/association_slot', curie: 'biolink:association_slot', label: 'association slot', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/association_type', curie: 'biolink:association_type', label: 'association type', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/base_coordinate', curie: 'biolink:base_coordinate', label: 'base coordinate', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/catalyst_qualifier', curie: 'biolink:catalyst_qualifier', label: 'catalyst qualifier', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/chi_squared_statistic', curie: 'biolink:chi_squared_statistic', label: 'chi squared statistic', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/clinical_modifier_qualifier', curie: 'biolink:clinical_modifier_qualifier', label: 'clinical modifier qualifier', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/end_coordinate', curie: 'biolink:end_coordinate', label: 'end coordinate', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/end_interbase_coordinate', curie: 'biolink:end_interbase_coordinate', label: 'end interbase coordinate', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/expression_site', curie: 'biolink:expression_site', label: 'expression site', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/frequency_qualifier', curie: 'biolink:frequency_qualifier', label: 'frequency qualifier', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/interacting_molecules_category', curie: 'biolink:interacting_molecules_category', label: 'interacting molecules category', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/interbase_coordinate', curie: 'biolink:interbase_coordinate', label: 'interbase coordinate', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/knowledge_source', curie: 'biolink:knowledge_source', label: 'knowledge source', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/logical_interpretation', curie: 'biolink:logical_interpretation', label: 'logical interpretation', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/mechanism_of_action', curie: 'biolink:mechanism_of_action', label: 'mechanism of action', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/negated', curie: 'biolink:negated', label: 'negated', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/object', curie: 'biolink:object', label: 'object', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/onset_qualifier', curie: 'biolink:onset_qualifier', label: 'onset qualifier', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/original_knowledge_source', curie: 'biolink:original_knowledge_source', label: 'original knowledge source', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/original_object', curie: 'biolink:original_object', label: 'original object', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/original_predicate', curie: 'biolink:original_predicate', label: 'original predicate', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/original_subject', curie: 'biolink:original_subject', label: 'original subject', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/p_value', curie: 'biolink:p_value', label: 'p value', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/phase', curie: 'biolink:phase', label: 'phase', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/phenotypic_state', curie: 'biolink:phenotypic_state', label: 'phenotypic state', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/predicate', curie: 'biolink:predicate', label: 'predicate', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/primary_knowledge_source', curie: 'biolink:primary_knowledge_source', label: 'primary knowledge source', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/provided_by', curie: 'biolink:provided_by', label: 'provided by', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/qualifiers', curie: 'biolink:qualifiers', label: 'qualifiers', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/quantifier_qualifier', curie: 'biolink:quantifier_qualifier', label: 'quantifier qualifier', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/reaction_balanced', curie: 'biolink:reaction_balanced', label: 'reaction balanced', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/reaction_direction', curie: 'biolink:reaction_direction', label: 'reaction direction', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/reaction_side', curie: 'biolink:reaction_side', label: 'reaction side', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/sequence_localization_attribute', curie: 'biolink:sequence_localization_attribute', label: 'sequence localization attribute', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/sequence_variant_qualifier', curie: 'biolink:sequence_variant_qualifier', label: 'sequence variant qualifier', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/severity_qualifier', curie: 'biolink:severity_qualifier', label: 'severity qualifier', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/sex_qualifier', curie: 'biolink:sex_qualifier', label: 'sex qualifier', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/stage_qualifier', curie: 'biolink:stage_qualifier', label: 'stage qualifier', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/start_coordinate', curie: 'biolink:start_coordinate', label: 'start coordinate', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/start_interbase_coordinate', curie: 'biolink:start_interbase_coordinate', label: 'start interbase coordinate', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/genome_build', curie: 'biolink:genome_build', label: 'genome build', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/strand', curie: 'biolink:strand', label: 'strand', type: 'BioLink'},
  {id: 'https://w3id.org/biolink/vocab/subject', curie: 'biolink:subject', label: 'subject', type: 'BioLink'},
]



// https://purl.org/np/RAuN1kyW1BD9754LCUVWozDOhkrUaLUyb5LTu0HcsulIE
const samples: any = {
  "Drug indication with the BioLink model": {
    "@context": "https://raw.githubusercontent.com/biolink/biolink-model/master/context.jsonld",
    "@wizardQuestions": {
      "rdf:subject": "Subject of the association:",
      "rdf:predicate": "Predicate of the association:",
      "rdf:object": "Object of the association:",
      "biolink:provided_by": "Association provided by dataset:",
      "biolink:publications": "Publication supporting the association:",
      "biolink:association_type": "Type of the association:",
      "biolink:relation": "Type of drug indication:",
      "biolink:has_population_context": "Population context of the drug indication:"
    },
    "@type": "rdf:Statement",
    "rdfs:label": "An atypical drug is now increasingly used as an off-label indication for the management of cancer patients",
    "rdf:subject": {
      "@id": "https://go.drugbank.com/drugs/DB00334",
      "@type": "biolink:Drug"
    },
    "rdf:predicate": {
      "@id": "biolink:treats"
    },
    "rdf:object": {
      "@id": "https://identifiers.org/HP:0002017",
      "@type": "biolink:Disease"
    },
    "biolink:association_type": {
      "@id": "biolink:ChemicalToDiseaseOrPhenotypicFeatureAssociation"
    },
    "biolink:relation": {"@id" : "https://w3id.org/um/neurodkg/OffLabelIndication"},
    "biolink:provided_by": {"@id" : "https://w3id.org/um/NeuroDKG"},
    "biolink:publications": {"@id" : "https://pubmed.ncbi.nlm.nih.gov/29061799/"},
    "biolink:has_population_context": {
      "rdfs:label": "Adults",
      "biolink:category": {"@id": "biolink:Cohort"},
      "biolink:has_phenotype": {
        "@id": "https://identifiers.org/MONDO:0004992",
        "@type": "biolink:Phenotype"
      }
    }
  },
  "Dataset summary with schema.org": {
    "@context": "https://schema.org",
    "@wizardQuestions": {
      "name": "Provide the name of this entity:",
      "description": "Give a short description of the content:",
      "creator": "Provide the details of the person who created, or initiated, the creation of this work:",
      "contributor": "Other persons who contributed to, or co-authored, the dataset:",
      "publisher": "Person, or organization, who published this work:",
      "inLanguage": "What language is used in the description of this dataset? Use ISO 2 language code e.g. EN for English",
      "version": "What is the version number for this dataset? e.g. 1.1.1 or v1.2",
      "license": "Link to the full text of the terms of use (license) for this dataset:",
      "encodingFormat": "What is the file format of this data?",
      "url": "Link to the website or homepage:",
      "temporalCoverage": "What is the creation or publishing date range for the documents or contents of this dataset? Use https://en.wikipedia.org/wiki/ISO_8601#Time_intervals format - e.g. 2007-03-01/2008-05-11:",
      "keywords": "Provide keywords describing the content in this dataset:",
      "distribution": "Supply a direct download link for this dataset:",
      "contentSize": "How large is the download file size e.g. 128KB, 54MB, 1.5GB?",
      "isBasedOn": "Was this dataset generated with the aid of or using a piece of software?",
      "applicationCategory": "Indicate type of software e.g. Python script or Java GUI application:",
      "citation": "Is there an academic publication which describes or centrally makes use of this dataset?",
      "datePublished": "On what date was the dataset published? YYYY-MM-DD",
      "dateCreated": "On what date was the dataset created? YYYY-MM-DD",
      "affiliation": "This person is affiliated to or employed by:",
      "logo": "Link to an image depicting the logo of this organisation:",
      "image": "Provide a link (URL) to a profile photo of the author of the dataset:",
      "sameAs": "Provide a Digital Object Identifier (DOI) for this publication:",
      "frequency": "How often does a new version get published for this dataset? e.g. daily, weekly, monthly"
    },
    "@type": "Dataset",
    "name": "ECJ case law text similarity analysis",
    "description": "results from a study to analyse how closely the textual similarity of ECJ cases resembles the citation network of the cases.",
    "version": "v2.0",
    "url": "https://doi.org/10.5281/zenodo.4228652",
    "license": "https://www.gnu.org/licenses/agpl-3.0.txt",
    "encodingFormat": "CSV",
    "temporalCoverage": "2019-09-14/2020-07-01",
    "dateCreated": {
        "@type": "Date",
        "@value": "2019-09-14"
    },
    "datePublished": {
        "@type": "Date",
        "@value": "2020-07-01"
    },
    "distribution": {
        "@type": "DataDownload",
        "contentUrl": {
            "@type": "URL",
            "@value": "https://zenodo.org/record/4228652/files/docona_cjeu_results_2018_v2_html.zip?download=1"
        },
        "encodingFormat": "application/zip",
        "contentSize": "1.1MB"
    },
    "inLanguage": {
        "@type": "Language",
        "name": "EN",
        "alternateName": "EN"
    },
    "keywords": [
        "case law",
        "court decisions",
        "text similarity",
        "network analysis"
    ],
    "creator": {
        "@type": "Person",
        "name": "concat @givenName @familyName",
        "givenName": "Kody",
        "familyName": "Moodley",
        "image": "https://www.maastrichtuniversity.nl/sites/default/files/styles/text_with_image_mobile_portrait/public/profile/kody.moodley/kody.moodley_photo_kmoodley.jpg?itok=bN7b8s_-&timestamp=1583505301",
        "jobTitle": "Postdoctoral researcher",
        "email": "kody.moodley@maastrichtuniversity.nl",
        "affiliation": {
            "@type": "Organization",
            "name": "Maastricht Law & Tech Lab",
            "url": {
                "@type": "URL",
                "@value": "https://www.maastrichtuniversity.nl/about-um/faculties/law/research/law-and-tech-lab"
            },
            "logo": {
                "@type": "ImageObject",
                "contentUrl": "https://www.maastrichtuniversity.nl/sites/default/files/styles/page_photo/public/compacte20versie20law20and20tech20lab.jpg?itok=7lm6PEQF"
            }
        }
    },
    "contributor": [
        {
            "@type": "Person",
            "givenName": "Pedro",
            "familyName": "Hernandez Serrano",
            "jobTitle": "Data Scientist",
            "email": "p.hernandezserrano@maastrichtuniversity.nl",
            "image": "https://www.maastrichtuniversity.nl/sites/default/files/styles/text_with_image_mobile_portrait/public/profile/p.hernandezserrano/p.hernandezserrano_PP%20%287%20of%2013%29.jpg?itok=IUdreoIw&timestamp=1610395201",
            "affiliation": {
                "@type": "Organization",
                "name": "Institute of Data Science",
                "url": {
                    "@type": "URL",
                    "@value": "https://www.maastrichtuniversity.nl/research/institute-data-science"
                },
                "logo": {
                    "@type": "ImageObject",
                    "contentUrl": "https://avatars.githubusercontent.com/u/36262526?s=280&v=4"
                }
            }
        }
    ],
    "publisher": {
        "@type": "Person",
        "name": "Kody Moodley",
        "givenName": "Kody",
        "familyName": "Moodley",
        "jobTitle": "Postdoctoral researcher",
        "image": "https://www.maastrichtuniversity.nl/sites/default/files/styles/text_with_image_mobile_portrait/public/profile/kody.moodley/kody.moodley_photo_kmoodley.jpg?itok=bN7b8s_-&timestamp=1583505301",
        "email": "kody.moodley@maastrichtuniversity.nl",
        "affiliation": {
            "@type": "Organization",
            "name": "Maastricht Law & Tech Lab",
            "url": {
                "@type": "URL",
                "@value": "https://www.maastrichtuniversity.nl/about-um/faculties/law/research/law-and-tech-lab"
            },
            "logo": {
                "@type": "ImageObject",
                "contentUrl": "https://www.maastrichtuniversity.nl/sites/default/files/styles/page_photo/public/compacte20versie20law20and20tech20lab.jpg?itok=7lm6PEQF"
            }
        }
    }
  }
}


// export default settings;
export {
  settings,
  getUrlHtml,
  samples,
  propertiesList,
  predicatesList,
}