#+ summary: List of curated drug indications from dailymed product labels using the knowledge collaboratory.
#+ description: A SPARQL query to retrieve a list of curated drug indications from dailymed product labels using the knowledge collaboratory.
#+ endpoint: https://virtuoso.nps.knowledgepixels.com/sparql
#+ endpoint_in_url: False
#+ tags:
#+   - Drug Discovery
prefix biolink: <https://w3id.org/biolink/vocab/>
prefix np: <http://www.nanopub.org/nschema#>
prefix npx: <http://purl.org/nanopub/x/>
prefix orcid: <https://orcid.org/>
prefix prov: <http://www.w3.org/ns/prov#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?subject_label ?object_label ?dailymed ?orcid ?quote
{
  GRAPH ?g {
  	?s rdf:predicate biolink:treats .
    ?s rdf:subject ?subject .
    ?s rdf:object ?object .
    ?subject rdfs:label ?subject_label .
    ?object rdfs:label ?object_label .
    ?s biolink:publications ?dailymed .
  }
  ?g prov:wasAttributedTo ?orcid .
  #FILTER (?orcid = orcid:0000-0003-4727-9435)

  ?g prov:wasQuotedFrom ?quote .
} GROUP BY ?dailymed
ORDER BY desc(?dailymed)
