name: Deploy frontend to GitHub Pages
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  #   paths:
  #   - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies and build
      env:
        API_URL: "https://api.collaboratory.semanticscience.org"
        FRONTEND_URL: "https://maastrichtu-ids.github.io/knowledge-collaboratory"
      run: |
        cd frontend
        yarn install
        yarn build
        yarn export

    # - name: Deploy on GitHub
    #   uses: JamesIves/github-pages-deploy-action@3.7.1
    #   with:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     BRANCH: gh-pages
    #     FOLDER: frontend/app/web-build
    #     CLEAN: true

    # - name: Deploy on GitHub
    #   run: yarn deploy

    # Docs: https://github.com/peaceiris/actions-gh-pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Build output to publish to the `gh-pages` branch:
        publish_dir: ./docs
        # The following lines assign commit authorship to the official
        # GH-Actions bot for deploys to `gh-pages` branch
        # The GH actions bot is used by default if you didn't specify the two fields.
        user_name: github-actions[bot]
        user_email: 41898282+github-actions[bot]@users.noreply.github.com
