name: Deploy frontend to GitHub Pages

on:
  push:
    branches: [main]
    paths:
    - 'frontend'
    - '.github/actions/deploy-frontend.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  PUBLIC_SITE_URL: https://maastrichtu-ids.github.io
  PUBLIC_BASE_URL: /knowledge-collaboratory

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3

      - name: Install, build, and upload your site
        uses: withastro/action@v0
        with:
          node-version: 18
          package-manager: yarn
          path: ./frontend

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
