name: Run backend tests

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  #   paths:
  #   - 'backend/**'
  #   - '.github/actions/test-backend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # - uses: actions/cache@v2
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        cd backend
        pip install poetry
        poetry install

    - name: Run tests
      run: |
        cd backend
        # ./tests-start.sh
        poetry run pytest --cov=app --cov-report=term-missing tests/integration
