name: Test production API
on:
  workflow_dispatch:
  schedule:
    - cron:  '00 01 * * *'
    # Everyday at 01:00am GMT+1
  # push:
  #   branches: [ master ]
  #   paths:
  #   - 'tests/queries/*'
  #   - 'tests/production/*'
  #   - '.github/workflows/run-tests-prod.yml'

jobs:

  tests-production:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pytest reasoner-validator
    #     pip install .

    - name: Install dependencies
      run: |
        cd backend
        pip install poetry
        poetry install

    - name: Test with pytest
      run: |
        cd backend
        poetry run pytest tests/production -s
